#pragma once 
// Auto-generated by GenerateBuildInfo.bat (Pre-Build Event) 
// DO NOT EDIT MANUALLY 
 
#define BUILD_GIT_REVISION "8d244f6" 
#define BUILD_GIT_BRANCH   "claude/infallible-dubinsky" 
#define BUILD_GIT_DATE     "2026-02-12 08:02:45 +0900" 
#define BUILD_TIMESTAMP    "2026-02-13  0:08:04.18" 
