@echo off
REM ============================================================================
REM  BuildInfo.h 자동 생성 스크립트 (Pre-Build Event에서 호출)
REM  빌드할 때마다 Git revision, branch, 타임스탬프를 헤더에 기록합니다.
REM ============================================================================

cd /d "%~dp0"

REM Git이 없으면 기본값 사용
where git >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo #pragma once > BuildInfo.h
    echo #define BUILD_GIT_REVISION "unknown" >> BuildInfo.h
    echo #define BUILD_GIT_BRANCH   "unknown" >> BuildInfo.h
    echo #define BUILD_TIMESTAMP    "%DATE% %TIME%" >> BuildInfo.h
    echo [BuildInfo] Git not found, using defaults.
    exit /b 0
)

REM Git 정보 수집
for /f "delims=" %%i in ('git rev-parse --short HEAD 2^>nul') do set GIT_REV=%%i
for /f "delims=" %%i in ('git rev-parse --abbrev-ref HEAD 2^>nul') do set GIT_BRANCH=%%i
for /f "delims=" %%i in ('git log -1 --format^=%%ci 2^>nul') do set GIT_DATE=%%i

if "%GIT_REV%"=="" set GIT_REV=unknown
if "%GIT_BRANCH%"=="" set GIT_BRANCH=unknown
if "%GIT_DATE%"=="" set GIT_DATE=unknown

REM BuildInfo.h 생성
echo #pragma once > BuildInfo.h
echo // Auto-generated by GenerateBuildInfo.bat (Pre-Build Event) >> BuildInfo.h
echo // DO NOT EDIT MANUALLY >> BuildInfo.h
echo. >> BuildInfo.h
echo #define BUILD_GIT_REVISION "%GIT_REV%" >> BuildInfo.h
echo #define BUILD_GIT_BRANCH   "%GIT_BRANCH%" >> BuildInfo.h
echo #define BUILD_GIT_DATE     "%GIT_DATE%" >> BuildInfo.h
echo #define BUILD_TIMESTAMP    "%DATE% %TIME%" >> BuildInfo.h

echo [BuildInfo] Generated: Rev=%GIT_REV% Branch=%GIT_BRANCH%
